name: image-to-3d-gen
channels: 
  - defaults 
  - conda-forge 
  - nvidia

dependencies: 
  - python=3.11
  - pip 
  - git  # Conda's git to avoid libffi conflicts
  - cmake=4.0.3
  - gcc=14.2.0
  - gxx=14.2.0
  - gcc_linux-64=14.2.0
  - cuda-toolkit=12.8
  - cuda-nvcc=12.8
  - ninja=1.13.0

